FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf

# FROM nginx:alpine -> Define a imagem base como nginx:alpine, que é uma imagem leve do Nginx baseada no Alpine Linux.

# COPY nginx.conf /etc/nginx/nginx.conf -> Copia o arquivo nginx.conf do diretório local para o diretório /etc/nginx/nginx.conf dentro do contêiner.
